on-cruise-control/courier

docker-compose.yaml, docker/dockerfiles/rails.Dockerfile, docker/dockerfiles/vite.Dockerfile
Docker configuration set for cruise control
=> fix: docker configuration with custom images

app/controllers/api/v1/external/conversations_controller.rb, db/seeds.rb
Sorting issue fixed for external messages.
=> fix: sorting issue fixed in message

enterprise/app/models/enterprise/concerns/user.rb
Fixed crash on pricing plan limit comparison
=> fix: fixed crash on pricing comparison

.dockerignore, config/vite.json, docker-compose.production.yaml, docker/Dockerfile, docker/dockerfiles/rails.Dockerfile, docker/entrypoints/rails.sh, package.json
- Updated **docker-compose.production.yaml** production docker configurations for local directory
- Updated **Dockerfile** for rails/sidekiq/redis/vite configurations
- Updated rails server initialisation file for setting up server/pg connection
=> fix: update docker configurations for production instance setup with external PG

app/fields/enterprise/account_limits_field.rb, app/javascript/dashboard/components-next/message/Message.vue, db/schema.rb, spec/controllers/api/v2/accounts_controller_spec.rb, spec/enterprise/controllers/enterprise/api/v2/accounts_controller_spec.rb, spec/models/conversation_spec.rb
=> fix: feedback regarding account and chat

enterprise/app/models/enterprise/account/plan_usage_and_limits.rb
The bug was caused by a validation issue that prevented updates to the account limit value. The validation logic has been corrected to allow proper value updates.
=> fix: bug related to account limit value updates.

app/jobs/schedule_handoff_label_change_job.rb, app/services/conversation_handoff_service.rb
Labels assignment issues fixed while stark to hand-off or vice versa.
=> fix: labels assignment issues

app/drops/conversation_drop.rb, app/mailers/administrator_notifications/conversation_handoff_mailer.rb, app/mailers/agent_notifications/conversation_handoff_mailer.rb, app/views/layouts/mailer/base.liquid, app/views/mailers/administrator_notifications/conversation_handoff_mailer/notify_handoff.liquid, app/views/mailers/agent_notifications/conversation_handoff_mailer/notify_handoff.liquid
Changed email template design & text.
=> fix: changed email template design & text

app/mailers/administrator_notifications/conversation_handoff_mailer.rb, app/mailers/agent_notifications/conversation_handoff_mailer.rb
=> fix: current account issue

app/controllers/concerns/stark/api_handler.rb
Descending sorting apply on recent messages on the basis of created_at.
=> fix: sorting issue

app/views/mailers/administrator_notifications/conversation_handoff_mailer/notify_handoff.liquid, app/views/mailers/agent_notifications/conversation_handoff_mailer/notify_handoff.liquid
Fixed notify handoff email styling issue for text color
=> fix: styling issue in handoff email

app/finders/conversation_finder.rb, app/helpers/filters/filter_helper.rb, app/javascript/dashboard/components-next/filter/ConversationFilter.vue, app/javascript/dashboard/components/ChatList.vue, app/javascript/dashboard/components/ChatListHeader.vue, app/javascript/dashboard/components/widgets/conversation/ConversationBasicFilter.vue, app/javascript/dashboard/components/widgets/conversation/FilterItem.vue, app/javascript/dashboard/helper/filterQueryGenerator.js, app/javascript/dashboard/store/modules/conversations/helpers.js, app/javascript/dashboard/store/modules/conversations/index.js, app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js, app/javascript/shared/composables/useFilter.js
Adding OPEN and PENDING as default filters for All conversations.
=> Feature: Setting open and pending as default filters

app/services/stark/follow_up_service.rb
=> fix: syntax error

app/controllers/concerns/stark/api_handler.rb, app/jobs/conversations/follow_up_job.rb, app/models/conversation.rb, app/models/message.rb, db/migrate/20250627053719_add_stopfollow_up_in_conversation.rb, lib/integrations/stark/processor_service.rb
=> feature: stop follow up message

app/controllers/api/v1/accounts/conversations/messages_controller.rb, app/controllers/platform/api/v1/messages_controller.rb, config/routes.rb
Code optimization and use of platform_api token
=> fix: updates to api

config/initializers/rack_attack.rb
Updating rack attack limit for widget
=> Fix: Updating rack attack limit for widget

app/controllers/concerns/stark/message_handler.rb
avatar_name for web-widget inbox
=> fix: avatar_name for web-widget inbox

app/controllers/platform/api/v1/messages_controller.rb, app/mailers/agent_notifications/booking_mailer.rb, app/models/inbox.rb, app/views/mailers/agent_notifications/booking_mailer/booking_notification.html.erb
✅ Refactored MessagesController
- Simplified send_email_notification action for better readability and maintainability.
- Extracted logic into private methods:
- send_booking_notifications
- send_template_notifications
- Added consistent JSON error responses via render_error helper.
- Improved logging for better traceability of email delivery issues.
✅ Added BookingMailer
- Created AgentNotifications::BookingMailer:
- Implements booking_notification method to send booking-related emails to agents.
✅ Created Booking Email Template
- Added HTML email view:
- app/views/mailers/agent_notifications/booking_mailer/booking_notification.html.erb
- Template includes booking details for agents.
=> feature: Adding booking notification to send-message API #CRUISE-232

app/views/mailers/agent_notifications/booking_mailer/booking_notification.html.erb
fix: sender name for template messages
=> fix: sender name for template messages

app/controllers/concerns/stark/api_handler.rb, app/controllers/concerns/stark/message_handler.rb, app/models/attachment.rb
=> feature: handling image response in stark

.github/workflows/production_release.yml
=> fix in production_release.yml file

app/javascript/sdk/IFrameHelper.js
=> remove sanitizeURL from IFrameHelper.js

app/services/stark/follow_up_service.rb
=> fixing the followup issues

app/javascript/dashboard/components-next/copilot/CopilotAssistantMessage.vue, app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue, app/jobs/agents/destroy_job.rb, app/jobs/internal/check_new_versions_job.rb, docker/Dockerfile
Merging staging to master
Resolved sentry issues
=> Merging staging to master

app/services/stark/follow_up_service.rb, config/installation_config.yml
Updating Stark end point for messages and follow-up messages
=> Fix: updating stark end-point

app/jobs/send_template_dm_job.rb
=> fix: message update

app/services/instagram/send_on_instagram_service.rb
fix: channel_class for instagram comment support
=> fix: channel_class for comment support

app/controllers/concerns/stark/message_handler.rb, app/models/message.rb, app/services/instagram/send_on_instagram_service.rb
Fixed title of images for instagram channel
=> fix: title for images on instagram
